# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- hw4_deployment

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      PYTHON_VERSION: '3.7'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install prerequisites'

- script: |
    export DBHOST=$(DBHOST)
    export DBUSER=$(DBUSER)
    export DBNAME=$(DBNAME)
    export DBPASS=$(DBPASS) 
    pushd '$(projectRoot)'
    python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
  displayName: 'Run tests'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftps://waws-prod-ch1-029dr.ftp.azurewebsites.windows.net'
    username: 'hiltonTodoList\$hiltonTodoList'
    password: 'XktAeWk20hsv8iA1nQZaJZTSHrQsavWCELFNkCu7jKd69sscTPbfRw6ouLtF'
    rootDirectory: 
    filePatterns: '**'
    remoteDirectory: '/upload/$(Build.BuildId)/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.SourcesDirectory)'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
#     replaceExistingArchive: true
#     verbose: # (no value); this input is optional
#   displayName: 'Build Zip'
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Free Trial(a3ecd3f4-f98b-4735-9414-a9430e185e7b)'
#     appType: 'webAppLinux'
#     appName: 'hiltonTodoList'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     runtimeStack: 'PYTHON|2.7'